name: Build
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: prepare workspace
        run: unset HOST && source env.sh && ns-package-install && ns-clone && ns-pull-install
      - name: switch to new workspace
        run: rm env.sh && cd /home/runner/dev-netsurf/workspace && source env.sh && cd netsurf && make TARGET=framebuffer
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            README.md
            /home/runner/dev-netsurf/workspace/netsurf/nsfb
