name: Build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Grab a temporary env.sh
        run: unset HOST && source env.sh && ns-package-install && ns-clone
      - name: update
        run: ns-pull-install
      - name: switch to new workspace
        run: rm env.sh && cd /home/runner/dev-netsurf/workspace && source env.sh && cd netsurf 
      - name: build framebuffer
        run: make TARGET=framebuffer
